defaults: &defaults
  docker:
    - image: circleci/node:8.11.3-browsers

shared_steps: &shared_steps
  steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install
    - save_cache:
        paths:
          - node_modules
          - ~/.meteor
          - ~/.npm
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: curl https://install.meteor.com | /bin/sh
    - run: meteor npm test
    - run:
        command: meteor npm run dev
        background: true
    - run: sleep 100 # Wait for app to run before starting e2e tests.
    - run: meteor npm run test-e2e

version: 2
jobs:
  build:
    <<: *defaults
    <<: *shared_steps
  stage:
    <<: *defaults
    <<: *shared_steps
    steps:
      - run: meteor npm run staging
  deploy:
    <<: *defaults
    <<: *shared_steps
    steps:
      - run: meteor npm run production

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /feature\/.*/
                - /refactor\/.*/
                - /bug\/.*/
                - /chore\/.*/
      - stage:
          filters:
            branches:
              only:
                - development
      - deploy:
          filters:
            branches:
              only:
                - master
